import "./globals.css";
import Logo from "./logo";

import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.variable}`}>
      <body
        className={`antialiased bg-[url('/images/home.png')] bg-no-repeat h-screen bg-cover`}
      >
        <header className="mx-10 py-7 h-[96px] flex justify-between items-center border-b-2 border-b-[#EEEEEE]">
          <Logo />
          <button className="border border-[#FFFFFF] bg-[#EEEEEE] p-[12px_24px_12px_24px] rounded-[48px]">
            Info
          </button>
        </header>
        {children}
      </body>
    </html>
  );
}
